#!/bin/bash

faces=(Panini Kautilya Maurya)
styles=(Regular Bold Italic "Bold Italic")
desc_long="Pan Devanagari font designed to support all the languages using the Devanagari script."

export nlci=$HOME/script/tools
source ${nlci}/prepare.bash

source ${nlci}/metadata.bash

for ufo in ${src}/*.ufo
do
    psfdeleteglyphs -i source/delete_glyphs.txt $ufo
done
echo "done producing UFO sources"
