#!/bin/bash

ufo=results/ufo
src=source
nlci=$HOME/work/nlci/projects/fonts/tools
# grep -E "faces|styles" wscript | grep = > wscript.py
rm -f *.sfd

smith distclean -l
smith configure -l
smith build -l

pushd ${ufo}
for ttf in *.ttf
do
    echo $ttf
    sfd="$(basename $ttf .ttf).sfd"
    fontforge -script ${nlci}/ttf2sfd.ff $ttf $sfd
done
popd

# sort -o cs/charis/pre.txt cs/charis/composite.txt cs/charis/decomposition.txt
# sort -o cs/gentium/pre.txt cs/gentium/composite.txt cs/gentium/decomposition.txt
# python addchars.py ${ufo}

pushd ${ufo}
for sfd in *.sfd
do
    echo $sfd
    ufo2="$(basename $sfd .sfd).ufo"
    fontforge -script ${nlci}/sfd2ufo.ff $sfd $ufo2
    psfnormalize -v 3 -p checkfix=none $ufo2
    ufo3=$ufo2
    ${nlci}/ufo_init.py $ufo3
done
popd

rm -rf ${src}/*.ufo
mv -v ${ufo}/*.ufo ${src}
mv -v ${ufo}/*.sfd ${src}
rm -rf ${src}/backups
